import { token } from '@/styled-system/tokens';

export const colors = {
  primitive: {
    gray: {
      50: token('colors.gray.50'),
      100: token('colors.gray.100'),
      200: token('colors.gray.200'),
      300: token('colors.gray.300'),
      400: token('colors.gray.400'),
      500: token('colors.gray.500'),
      600: token('colors.gray.600'),
      700: token('colors.gray.700'),
      800: token('colors.gray.800'),
      900: token('colors.gray.900'),
    },
    blue: {
      50: token('colors.blue.50'),
      100: token('colors.blue.100'),
      200: token('colors.blue.200'),
      300: token('colors.blue.300'),
      400: token('colors.blue.400'),
      500: token('colors.blue.500'),
      600: token('colors.blue.600'),
      700: token('colors.blue.700'),
      800: token('colors.blue.800'),
      900: token('colors.blue.900'),
    },
    red: {
      50: token('colors.red.50'),
      100: token('colors.red.100'),
      200: token('colors.red.200'),
      300: token('colors.red.300'),
      400: token('colors.red.400'),
      500: token('colors.red.500'),
      600: token('colors.red.600'),
      700: token('colors.red.700'),
      800: token('colors.red.800'),
      900: token('colors.red.900'),
    },
    green: {
      50: token('colors.green.50'),
      100: token('colors.green.100'),
      200: token('colors.green.200'),
      300: token('colors.green.300'),
      400: token('colors.green.400'),
      500: token('colors.green.500'),
      600: token('colors.green.600'),
      700: token('colors.green.700'),
      800: token('colors.green.800'),
      900: token('colors.green.900'),
    },
    orange: {
      50: token('colors.orange.50'),
      100: token('colors.orange.100'),
      200: token('colors.orange.200'),
      300: token('colors.orange.300'),
      400: token('colors.orange.400'),
      500: token('colors.orange.500'),
      600: token('colors.orange.600'),
      700: token('colors.orange.700'),
      800: token('colors.orange.800'),
      900: token('colors.orange.900'),
    },
    pink: {
      50: token('colors.pink.50'),
      100: token('colors.pink.100'),
      200: token('colors.pink.200'),
      300: token('colors.pink.300'),
      400: token('colors.pink.400'),
      500: token('colors.pink.500'),
      600: token('colors.pink.600'),
      700: token('colors.pink.700'),
      800: token('colors.pink.800'),
      900: token('colors.pink.900'),
    },
    white: token('colors.white'),
    black: token('colors.black'),
    yellow: token('colors.yellow'),
  },
  brand: {
    primary: token('colors.brand.primary'),
    primaryLight: token('colors.brand.primaryLight'),
    primaryDark: token('colors.brand.primaryDark'),
  },
  contents: {
    primary: token('colors.contents.primary'),
    secondary: token('colors.contents.secondary'),
    tertiary: token('colors.contents.tertiary'),
    disabled: token('colors.contents.disabled'),
    inverse: token('colors.contents.inverse'),
    link: token('colors.contents.link'),
    linkHover: token('colors.contents.linkHover'),
    error: token('colors.contents.error'),
    success: token('colors.contents.success'),
    warning: token('colors.contents.warning'),
  },
  background: {
    default: token('colors.bg.primary'),
    paper: token('colors.bg.secondary'),
    subtle: token('colors.bg.tertiary'),
    hover: token('colors.bg.hover'),
    active: token('colors.bg.active'),
    disabled: token('colors.bg.disabled'),
  },
  border: {
    default: token('colors.border.default'),
    subtle: token('colors.border.subtle'),
    strong: token('colors.border.strong'),
    hover: token('colors.border.hover'),
    focus: token('colors.border.focus'),
    error: token('colors.border.error'),
    success: token('colors.border.success'),
    warning: token('colors.border.warning'),
  },
  focus: {
    ring: token('colors.blue.500'),
    background: token('colors.yellow'),
    outline: token('colors.black'),
    text: token('colors.black'),
  },
  feedback: {
    error: {
      bg: token('colors.red.50'),
      border: token('colors.red.300'),
      text: token('colors.red.800'),
      icon: token('colors.red.600'),
    },
    success: {
      bg: token('colors.green.50'),
      border: token('colors.green.300'),
      text: token('colors.green.800'),
      icon: token('colors.green.600'),
    },
    warning: {
      bg: token('colors.orange.50'),
      border: token('colors.orange.300'),
      text: token('colors.orange.900'),
      icon: token('colors.orange.600'),
    },
    info: {
      bg: token('colors.blue.50'),
      border: token('colors.blue.300'),
      text: token('colors.blue.800'),
      icon: token('colors.blue.600'),
    },
  },
} as const;

export const primitive = colors.primitive;
